#!/bin/sh

source ./menu_ex

# ---------------------------------------------------------------------------------------------------------------------
#
# Demo Example:
#
# run 'dev' alias to see all the demo menus
#
# ---------------------------------------------------------------------------------------------------------------------

DEMO.Create() {
    null='MENU.Null'

    #
    # Demo menu 'PLATFORM'
    #

    # -----------------------------------------------------------------------------------------------------------------
    # Create a menu
    #
    # 1           handle                     - a name/handle of the menu to be used w/ the API
    # 2 [OPT]       |     name               - a displayed name of the menu
    # 3 [OPT]       |      |    alias        - an alias to be created that displays the menu
    # 4 [OPT]       |      |     |  callback - a function to be called when the menu is displayed
    MENU.Create pl_menu PLATFORM PL DEMO.MainMenuCallback
    #MENU.Create pl_menu $null PL MENU.DemoMainMenu
    #MENU.Create pl_menu $null $null MENU.DemoMainMenu
    #MENU.Create pl_menu

    # -----------------------------------------------------------------------------------------------------------------
    # Under the hood 'PL' is just an alias for: 'MENU.Show pl_menu'
    #
    # 1 [OPT]  flag1           - whether to call the main menu's callback
    # 2 [OPT]   |    flag2     - whether to call the selected radio button item's callback
    # 3 [OPT]   |     |   mode - call-mode of all the check button item's callbacks, for modes see documentation for .Show
    # > PL    false false all
    #
    # 'PL' alias usage examples:
    # > PL                 - displays the menu
    # > PL true            - displays the menu + calls the menu's callback
    # > PL false true      - displays the menu + calls the selected radio button item's callback
    # > PL true true       - displays the menu + calls both the selected item and the main menu's callbacks
    # > PL false false all - displays the menu + calls all the radio button item's callbacks
    # -----------------------------------------------------------------------------------------------------------------

    # -----------------------------------------------------------------------------------------------------------------
    # Set the menu's style (replace the default style)
    #
    # 1           handle                                               - a name/handle of the menu to be used w/ the API
    # 2 [OPT]       |    divider                                       - devider to be used w/ .AddDivider ('|' by default)
    # 3 [OPT]       |      |        alignment                          - alignent of the item names (none by default)
    # 4 [OPT]       |      |           |          color                - the color of hightlighted items (green by default)
    # 5 [OPT]       |      |           |            |  symbol1       - the select symbol for the radio button when selected
    # 6 [OPT]       |      |           |            |   |  symbol2 - the check symbol for the check button when checked
    #MENU.SetStyle pl_menu default by.largest.item red '○' default
    #MENU.SetStyle pl_menu default by.largest.item
    # -----------------------------------------------------------------------------------------------------------------

    # -----------------------------------------------------------------------------------------------------------------
    # Set the extra style of the menu (replace the default style)
    # 1            handle                                                  - a name/handle of the menu to be used w/ the API
    # 2 [OPT]         |     separator.show                                 - {true/false} whether to print the menu's separator (true by default)
    # 3 [OPT]         |       |  separator.symbol                          - separator symbol ('-' by default)
    # 4 [OPT]         |       |    |  name.header                          - menu's name header (' * ' by default)
    # 5 [OPT]         |       |    |    |  name.footer                     - menu's name footer (':' by default)
    # 6 [OPT]         |       |    |    |    | symbol.radio.start          - radio.button opening symbol ('(' by default)
    # 7 [OPT]         |       |    |    |    |   | symbol.radio.end        - radio.button closing symbol (')' by default)
    # 8 [OPT]         |       |    |    |    |   |   | symbol.chk.start    - check.button opening symbol ('[' by default)
    # 9 [OPT]         |       |    |    |    |   |   |   |  symbol.chk.end - check.button closing symbol (']' by default)
    #MENU.SetStyleEx pl_menu true '-' " * " ":" '(' ')' '[' ']'
    #
    # For example:
    #
    #MENU.SetStyleEx pl_menu true '=' " + '" "':" '[[' ']]' '((' '))'
    #MENU.SetStyle pl_menu default by.largest.item cyan 'xx' '***'
    # -----------------------------------------------------------------------------------------------------------------

    # -----------------------------------------------------------------------------------------------------------------
    # Add a radio.button item into the menu
    #
    # 1               handle                    - a name/handle of the menu to be used w/ the API
    # 2                 |    name               - an item's name to be added into the menu
    # 3 [OPT]           |     |    alias        - an alias to be created that triggers the item's callback
    # 4 [OPT]           |     |     |  callback - a function to be called when an item is selected
    MENU.AddRadioButton pl_menu Linux nux DEMO.PlLinuxCallback
    #MENU.AddRadioButton pl_menu Linux $null MENU.DemoPlLinuxCb
    #MENU.AddRadioButton pl_menu Linux
    #
    # In the invocation example #2, there is no alias for item 'Linux', so the only way to call it is by using
    # the .Select command, like so: MENU.Select pl_menu Linux true false true
    # Please, look into .Select command demo to understand all the flags
    #
    # -----------------------------------------------------------------------------------------------------------------
    # Under the hood 'nux' is just an alias for: 'MENU.Select pl_menu Linux true false true'
    #
    # 1 [OPT]  flag1     - whether to call the main menu's callback
    # 2 [OPT]   |   mode - call-mode of the check button callbacks [no (false), all (true), checked, unchecked]
    # > nux    true no
    #
    # 'nux' alias usage examples:
    # > nux          - selects 'Linux' item, displays the 'PLATFORM' menu and triggers the 'Linux' item's callback
    # > nux true     - all the above + triggers the 'PLATFORM' menu's callback
    # > nux true all - all the above + triggers all the check button item's callbacks (if any)
    # -----------------------------------------------------------------------------------------------------------------

    MENU.AddRadioButton pl_menu rpi3 pi3 DEMO.PlRpi3Callback
    MENU.AddDivider pl_menu
    #MENU.AddLnBreak pl_menu
    MENU.AddLabel pl_menu QEMU:
    MENU.AddRadioButton pl_menu v8 v8 DEMO.PlQemuCallback
    MENU.AddRadioButton pl_menu arm32 arm DEMO.PlQemuCallback
    #MENU.AddDivider pl_menu
    #MENU.AddRadioButton pl_menu "Name w/ space" ace MENU.DemoPlQemuCb

    # -----------------------------------------------------------------------------------------------------------------
    # Select an item of the menu
    #
    #           handle                             - a name/handle of the menu to be used w/ the API
    #             |    name                        - a name of an item to be set as 'selected' in the menu
    #             |     |   show                   -
    #             |     |    |    flag1            -
    #             |     |    |     |    flag2      -
    #             |     |    |     |     |    mode -
    MENU.Select pl_menu rpi3 false false true no
    # -----------------------------------------------------------------------------------------------------------------

    # -----------------------------------------------------------------------------------------------------------------
    # Create a menu which will be a sub menu for the PLATFORM menu
    # -----------------------------------------------------------------------------------------------------------------
    MENU.Create pl_sub_menu $null $null DEMO.PlSubMenuCallback
    MENU.AddRadioButton pl_sub_menu Item1 m1 DEMO.PlSubMenuRadioCallback
    MENU.AddRadioButton pl_sub_menu Item2 m2 DEMO.PlSubMenuRadioCallback
    MENU.AddRadioButton pl_sub_menu Item3 m3 DEMO.PlSubMenuRadioCallback

    #MENU.AddLnBreak pl_sub_menu
    MENU.AddDivider pl_sub_menu
    MENU.AddLabel pl_sub_menu Mode:
    MENU.AddCheckButton pl_sub_menu Ps1 s1 DEMO.PlSubMenuCheckCallback
    MENU.AddCheckButton pl_sub_menu Nx Nx DEMO.PlSubMenuCheckCallback
    MENU.Select pl_sub_menu Item2 false
    MENU.Select pl_sub_menu Ps1 false
    # -----------------------------------------------------------------------------------------------------------------

    #MENU.AddDivider pl_menu
    MENU.AddLnBreak pl_menu
    MENU.AddMenu pl_menu pl_sub_menu

    # -----------------------------------------------------------------------------------------------------------------
    # Show/display the menu
    #
    #           handle                - a name/handle of the menu to be used w/ the API
    #             |   flag1           - whether to call the main menu's callback
    #             |     |  flag2      - whether to call the selected radio button item's callback
    #             |     |    |   mode - call mode of the check button callbacks [no (false), all (true), checked, unchecked]
    #MENU.Show pl_menu true true all

    #
    # mode:
    #  no (false)   - do not call any callback for any check button itmes
    #  all (true)   - call all the callbacks for all check button items regardless of the state
    #  current      - call the callback of the check button item that changes the state (.Select only)
    #  checked      - call all the callbacks for all checked check button items
    #  unchecked    - call all the callbacks for all un-checked check button items
    #
    # -----------------------------------------------------------------------------------------------------------------
:'
    MENU.Create build_menu Build Build MENU.DemoMainMenu

    #
    # if there is no alias for the menu you can call it through
    # MENU API directly or create your own alias:
    #
    # > MENU.Show build_menu
    #

    #
    # Demo menu 'Build'
    #
    MENU.AddRadioButton build_menu Debug debug MENU.DemoBuildChange
    MENU.AddRadioButton build_menu Release release MENU.DemoBuildChange
    MENU.AddDivider build_menu
    MENU.AddCheckButton build_menu Pedantic Pedant MENU.DemoBuildGccFlags
    MENU.AddCheckButton build_menu Wall all MENU.DemoBuildGccFlags
    MENU.AddCheckButton build_menu Werror err MENU.DemoBuildGccFlags
    MENU.AddCheckButton build_menu fPIC PIC MENU.DemoBuildGccFlags
    MENU.AddCheckButton build_menu isoC99 iso MENU.DemoBuildGccFlags
    MENU.Select build_menu Debug false
    MENU.Select build_menu Wall false
    MENU.Select build_menu Werror false
    #MENU.Show build_menu true true all

    #
    # Demo menu 'LOGS'
    #

    MENU.Create logs_menu LOGS LOGS MENU.DemoMainMenu
    MENU.SetStyle logs_menu default by.largest.item

    MENU.AddRadioButton logs_menu FATAL $null MENU.DemoLogsCb
    MENU.AddRadioButton logs_menu SEVERE $null MENU.DemoLogsCb
    MENU.AddRadioButton logs_menu WARNING $null MENU.DemoLogsCb
    MENU.AddRadioButton logs_menu INFO $null MENU.DemoLogsCb
    MENU.AddLnBreak logs_menu
    MENU.AddRadioButton logs_menu FINE $null MENU.DemoLogsCb
    MENU.AddRadioButton logs_menu FINER $null MENU.DemoLogsCb
    MENU.AddRadioButton logs_menu FINEST $null MENU.DemoLogsCb
    MENU.AddRadioButton logs_menu OFF $null MENU.DemoLogsCb


    MENU.Select logs_menu INFO false
    #MENU.Show logs_menu true true
'
    MENU._debug_print_all
}

# -----------------------------------------------------------------------------------------------------------------
# The Demo Menu's Callbacks
# -----------------------------------------------------------------------------------------------------------------

# [IN] handle - the menu's name/handle
# [IN] name   - the menu's name (if specified)
DEMO.MainMenuCallback() {
    #MENU._separator $1
    echo " PL.$2..."
    echo ' ...'
}

# [IN] handle - the menu's name/handle
# [IN] name   - the item's selected
DEMO.PlLinuxCallback() {
    if [ "$2" != 'Linux' ]; then
        MENU._error "Wrong callback!"
        return
    fi
    #MENU._separator $1
    echo " PL.Linux.Callback..."
    echo ' ...'
}

DEMO.PlRpi3Callback() {
    #MENU._separator $1
    echo " PL.$2.Callback..."
    echo ' ...'
}

DEMO.PlQemuCallback() {
    #MENU._separator $1
    echo " PL.$2..."
    echo ' ...'
}

# -----------------------------------------------------------------------------------------------------------------

DEMO.PlSubMenuCallback() {
    echo " PL.SubMenu..."
    echo ' ...'
}

DEMO.PlSubMenuRadioCallback() {
    #MENU._separator $1
    echo " PL.SubMenu.$2..."
    echo ' ...'
}

# [IN]      handle - the menu's name/handle
# [IN]      name   - the name of the selected item
# [IN][OPT] state  - {on, off} item's state (check.button type only)
DEMO.PlSubMenuCheckCallback() {
    #MENU._separator $1
    echo " PL.SubMenu.$2.[$3]..."
    echo ' ...'
}

# -----------------------------------------------------------------------------------------------------------------

DEMO.BuildChange() {
    #MENU._separator $1
    echo " Build.$2.Callback..."

    case $2 in
        Debug)
            echo ' ...'
            ;;
        Release)
            echo ' ...'
            ;;
    esac

}

MENU.DemoBuildGccFlags() {
    #MENU._separator $1
    echo " PL.$2.state.[$3].Callback..."

    case $2 in
        Pedantic)
            echo ' ...'
            ;;
        Wall)
            echo ' ...'
            ;;
        Werror)
            echo ' ...'
            ;;
        fPIC)
            echo ' ...'
            ;;
        isoC99)
            echo ' ...'
            ;;
    esac

}

MENU.DemoLogsCb() {
    #MENU._separator $1
    echo " LOGS.$2.Callback..."

    case $2 in
        FATAL)
            echo ' ...'
            ;;
        SEVERE)
            echo ' ...'
            ;;
        WARNING)
            echo ' ...'
            ;;
        INFO)
            echo ' ...'
            ;;
        FINE)
            echo ' ...'
            ;;
        FINER)
            echo ' ...'
            ;;
        FINEST)
            echo ' ...'
            ;;
        OFF)
            echo ' ...'
            ;;
    esac
}

# -----------------------------------------------------------------------------------------------------------------

alias dev='MENU.ShowAll true'

DEMO.Create

# Display all the menus and calls all the item's callbacks, which sets
# the environment, controlled by the menus, into the default state
MENU.ShowAll true true true all
