#!/bin/bash

# -----------------------------------------------------------------------------
#
# Demo menu 'Build'
#
# Aliases:
#
#   'dev'   - to display all the demo menus
#   'Build' - shows Build menu
#   'flip'  - flips all the check boxes in the menu
#             (shows how .CheckButtonForAll function can be used)
#
# -----------------------------------------------------------------------------

MENU_BuildCallback() {
    echo " $1.$2..."
    echo ' ...'
    # do something
}

MENU_BuildModeCallback() {
    echo " $1.$2..."
    case $2 in
        Debug)
            # do something
            echo ' ...'
            ;;
        Release)
            # do something
            echo ' ...'
            ;;
    esac
}

MENU_BuildGccFlagsCallback() {
    echo " $1.$2.state.[$3]..."
    case $2 in
        Pedantic)
            # do something
            echo ' ...'
            ;;
        Wall)
            # do something
            echo ' ...'
            ;;
        Werror)
            # do something
            echo ' ...'
            ;;
        fPIC)
            # do something
            echo ' ...'
            ;;
        isoC99)
            # do something
            echo ' ...'
            ;;
    esac
}

DEMO_CreateBuildMenu() {
    MENU_Create build_menu Build Build MENU_BuildCallback
    #MENU_SetStyle build_menu default none light.blue
    #MENU_SetStyle build_menu default none custom.background custom.foreground custom.highlighter

    MENU_AddRadioButton build_menu Debug debug MENU_BuildCallback
    MENU_AddRadioButton build_menu Release release MENU_BuildModeCallback
    MENU_AddDivider build_menu
    MENU_AddCheckButton build_menu Pedantic Pedant MENU_BuildGccFlagsCallback
    MENU_AddCheckButton build_menu Wall all MENU_BuildGccFlagsCallback
    MENU_AddCheckButton build_menu Werror err MENU_BuildGccFlagsCallback
    MENU_AddCheckButton build_menu fPIC PIC MENU_BuildGccFlagsCallback
    MENU_AddCheckButton build_menu isoC99 iso MENU_BuildGccFlagsCallback

    MENU_Select build_menu Debug false
    MENU_Select build_menu Wall false
    MENU_Select build_menu Werror false

    #MENU_debug_print_all
}

DEMO_CreateBuildMenu
alias dev='MENU_ShowAll true'

# Display all the menus and calls all the item's callbacks, which sets the environment,
# controlled by the menus. It's like setting everything up into a default state
#MENU_ShowAll true true true all

# Some cool stuff that you can do with the MENU class
alias flip='MENU_separator build_menu; MENU_CheckButtonForAll build_menu flip true false false all; MENU_separator build_menu'
